# Generated by Django 5.1.1 on 2024-09-24 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offlearn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user_course',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
