# Generated by Django 5.1.1 on 2024-09-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offlearn', '0002_course_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profile_image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
