# Generated by Django 5.1.1 on 2024-09-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offlearn', '0013_alter_course_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
    ]
