# Generated by Django 5.1.1 on 2024-09-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offlearn', '0014_alter_material_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offlearn.choice'),
        ),
    ]
