# Generated by Django 5.1.1 on 2024-09-29 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offlearn', '0015_alter_material_file_path_alter_studentanswer_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offlearn.quiz'),
            preserve_default=False,
        ),
    ]
