# Generated by Django 5.1.1 on 2024-10-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offlearn', '0018_alter_user_info_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profile_image',
            field=models.ImageField(default='/media/default.jpg', upload_to=''),
        ),
    ]
