# Generated by Django 5.1.2 on 2024-10-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offlearn', '0018_alter_user_info_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profile_image',
            field=models.ImageField(default='/media/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='role',
            field=models.CharField(choices=[('Student', 'Stu'), ('Instructor', 'Instruc')], max_length=20),
        ),
    ]
