# Generated by Django 5.1.1 on 2024-09-26 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offlearn', '0012_alter_course_course_image_alter_course_user_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_course',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
